[workspace]
resolver = "2"

members = [
  "crates/inel",
  "crates/inel-interface",
  "crates/inel-executor",
  "crates/inel-reactor",
]

[workspace.dependencies]
flume = "0.11"
futures = "0.3"
io-uring = "0.6"
libc = "0.2"
oneshot = "0.1"
tracing = "0.1"
pin-project-lite = "0.2"
slab = "0.4"
