[package]
name = "inel"
version = "0.1.0"
edition = "2021"

[dependencies]
inel-interface = { path = "../inel-interface" }
inel-executor = { path = "../inel-executor" }
inel-reactor = { path = "../inel-reactor" }
inel-macro = { path = "../inel-macro" }
