[package]
name = "inel"
version = "0.1.0"
edition = "2021"

[features]
default = ["sys"]
sys = []

[dependencies]
inel-interface = { path = "../inel-interface" }
inel-executor = { path = "../inel-executor" }
inel-reactor = { path = "../inel-reactor" }
inel-macro = { path = "../inel-macro" }
futures = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
# tests
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.41"
oneshot = "0.1"
uuid = { version = "1.10.0", features = ["v4"] }
rand = "0.8"

# server example
hyper = { version = "1", features = ["full"] }
http-body-util = "0.1"
hyper-util = { version = "0.1", features = ["full"] }
pin-project-lite = "0.2"
